modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="rpgmc"
version="1.0.0"
displayName="RPGMC"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="cuted, MCreator"

[[dependencies.rpgmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




